### PR TITLE
Added a workflow for automatic tagging on publish

### PR DESCRIPTION
**Pull request by IamLRBA**
# Explanation of the GitHub Actions Workflow: Tag on Publish

The Tag on Publish workflow I created is designed to automatically create a Git tag whenever changes are pushed to a specified branch that represents the published version of the website. This automation serves to document and track changes to the website over time, enhancing version control and facilitating easier rollbacks if necessary.
Workflow Breakdown

- **Trigger Event**: The workflow is triggered by a push event to a specified branch (e.g., published). This ensures that the tag creation only occurs when actual changes are made to the published version of the website.

- **Checkout the Repository**: The workflow starts by checking out the repository code using the `actions/checkout@v2` action. This gives the workflow access to the latest codebase to create the tag.

- **Set Up Date for Tag**: A step is included to generate a timestamp in the format `YYYYMMDDHHMM`, which captures the exact date and time when the tag is created. This timestamp is stored in the environment variable `TAG_DATE`.

- **Create and Push Tag**: The final step creates a new Git tag using the generated timestamp. The tag is formatted as `publishedYYYYmmddhhmm`, effectively documenting the version of the website at that specific moment. The tag is then pushed to the remote repository.
  
Git configuration is performed to set the user name and email for the tag creation, using the GitHub Actions bot identity.

## Conclusion

Implementing this GitHub Actions workflow effectively addresses the issue of documenting changes to the website by ensuring that a new tag is created automatically whenever updates are made to the published branch. This not only enhances the management of the codebase but also improves collaboration among developers, as everyone can easily see the history of changes made to the website.

### CODE REVIEW

**Comment by IamLRBA** [comment]
cc
@szarnekow Plesae review the code and if it passes, you can merge.
Thanks!

**Comment by LorenzoBettini** [comment]
The branch Is wrong: it's not "xtext-website"

**Comment by IamLRBA** [comment]
@LorenzoBettini Which one should i use as the brand?

**Comment by LorenzoBettini** [comment]
You wrote that yourself in the description and it was also in the corresponding issue: published.

Sorry if I ask but have you used some kind of chatgpt or the likes?

**Pull request closed without merging**
